### ISSUE TITLE
External config in js file wrongly evaluated

### ISSUE THREAD

**Issue by ThaNico** [OWASP/www-project-csrfguard#17] opened 2021-06-08 07:48 UTC
**Describe the bug**
Hello,
It looks like the external config variables in csrfguard.js are not properly applied.
I've had this issue with the %TOKENS_PER_PAGE% variable (org.owasp.csrfguard.TokenPerPage property)

**To Reproduce**
1. Simply set the property org.owasp.csrfguard.TokenPerPage to false
2. Then navigate to a web page

**Expected behavior**
The token per page should not be applied (and we shouldn't go inside its code)

**Screenshots**
Will add a screenshot below on the additional context

**Desktop :**
 - OS: [windows 10]
 - Browser [chrome]
 - Version [91]

**Additional context**
When the TokenPerPage property is set to false, the following js code on line 719 is evaluated to if('false') (which is actually true)
![image](https://user-images.githubusercontent.com/9906385/121143991-e24a1c00-c83d-11eb-8b42-10fc4c7afb5b.png)

There you can see the debugger going inside the condition (true or false doesnt matter) : 
![image](https://user-images.githubusercontent.com/9906385/121144222-14f41480-c83e-11eb-9965-6ad49126951b.png)

So I think you should rollback to what was done in csrfguard 3 : if(%TOKENS_PER_PAGE% == true) 
(Or maybe just : if(%TOKENS_PER_PAGE%) )

I think the other conditions have the same issue but I haven't checked

Thank you

**Comment by aramrami** [comment] 2021-06-08 07:53
Hello,
Thanks we will check that and try to make a correction.

**Comment by forgedhallpass** [comment] 2021-06-08 08:19
Hello @ThaNico,

I don't currently have Chrome on my machine, but I've tested it with FF and Safari and it was working as expected.

The value of the _TOKENS_PER_PAGE_IDENTIFIER_ is wrapped between single quotes, hence when it's replaced with a _true_ or _false_ value, it won't appear as string within the JavaScript code.

JavaScriptServlet.java:
```java
private static final String TOKENS_PER_PAGE_IDENTIFIER = "'%TOKENS_PER_PAGE%'";
// ...
.replace(TOKENS_PER_PAGE_IDENTIFIER, Boolean.toString(csrfGuard.isTokenPerPageEnabled()))
```

csrfguard.js:
```javascript
if ('%TOKENS_PER_PAGE%') {
...
```

See the attached screenshot below:

![token_per_page_false](https://user-images.githubusercontent.com/13679401/121147760-d6645700-c849-11eb-862f-6df99acef5b5.png)

I will close this because I wasn't able to reproduce it. Please make sure that you are using the latest version of the code (including the JS), try and test it out with the provided test application and maybe a different browser as well (although testing has been done on Chrome as well) and let me know if you run into any issues.

**Closed by forgedhallpass** 2021-06-08 08:19 UTC

**Comment by ThaNico** [comment] 2021-06-08 09:10
Indeed the js file was okay but there was a packaging issue with the jar from my side
Sorry for the wrong issue, I didn't think to check that
Have a nice day
